Web/Models/BuyFormModel.cs
using Auto.Product;

namespace Web.Models
{
    public class BuyFormModel
    {
        public IReadOnlyDictionary<string, string[]> MarkModelsDictionary { get; }

        public IReadOnlyCollection<string> Marks { get; }

        public IReadOnlyCollection<string> Models { get; }

        public int MaxCount { get; }
        public BuyFormModel(IReadOnlyCollection<CarProduct> carProducts)
        {
            MarkModelsDictionary = carProducts.ToLookup(product => product.Subject.Mark, product => product.Subject.Model)
                .ToDictionary(product => product.Key, product => product.ToArray());

            Marks = carProducts.Select(carProduct => carProduct.Subject.Mark).Distinct().ToArray();

            Models = carProducts.Select(carProduct => carProduct.Subject.Model).Distinct().ToArray();

            MaxCount = carProducts.Max(carProduct => carProduct.Count);
        }
    }
}

Web/Models/SellFormModel.cs
using Auto.Product;

namespace Web.Models
{
    public class SellFormModel
    {
        public IReadOnlyDictionary<string, string[]> MarkModelsDictionary { get; }

        public IReadOnlyCollection<string> Marks { get; }

        public IReadOnlyCollection<string> Models { get; }

        public SellFormModel(IReadOnlyCollection<CarProduct> carProducts)
        {
            MarkModelsDictionary = carProducts.ToLookup(product => product.Subject.Mark, product => product.Subject.Model)
                .ToDictionary(product => product.Key, product => product.ToArray());

            Marks = carProducts.Select(carProduct => carProduct.Subject.Mark).Distinct().ToArray();

            Models = carProducts.Select(carProduct => carProduct.Subject.Model).Distinct().ToArray();

        }
    }
}

Web/ViewModels/AdminViewModel.cs
using Auto.Product;

public class AdminViewModel
{
    public AdminViewModel(CarProduct[] carProducts)
    {
        Products = carProducts;
    }

    public CarProduct[] Products { get; }
}

Web/ViewModels/BuyFormViewModel.cs
using Auto.Product;

namespace Web.ViewModels
{
    public class BuyFormViewModel
    {

        public IReadOnlyCollection<string> Marks { get; }

        public IReadOnlyCollection<string> Models { get; }

        public int MaxCount { get; }
        public BuyFormViewModel(IReadOnlyCollection<CarProduct> carProducts)
        {

            Marks = carProducts.Select(carProduct => carProduct.Subject.Mark).Distinct().ToArray();

            Models = carProducts.Select(carProduct => carProduct.Subject.Model).Distinct().ToArray();

            MaxCount = carProducts.Any() ? carProducts.Max(carProduct => carProduct.Count) : 0;
        }
    }
}

Web/ViewModels/IndexViewModel.cs
using Auto.Product;
using Web.Models;

namespace Web.ViewModels;

public class IndexViewModel
{
    public CarProduct[] Products { get; }
    public BuyFormViewModel BuyFormViewModel { get; }
    public SellFormModel SellFormViewModel { get; }
    public IndexViewModel(CarProduct[] products)
    {
        Products = products;
        BuyFormViewModel = new (products);
        SellFormViewModel = new (products);
    }
}

Web/ViewModels/SellFormViewModel.cs
using Auto.Product;

namespace Web.Models
{
    public class SellFormModel
    {
        public IReadOnlyCollection<string> Marks { get; }

        public IReadOnlyCollection<string> Models { get; }

        public SellFormModel(IReadOnlyCollection<CarProduct> carProducts)
        {
          
            Marks = carProducts.Select(carProduct => carProduct.Subject.Mark).Distinct().ToArray();

            Models = carProducts.Select(carProduct => carProduct.Subject.Model).Distinct().ToArray();

        }
    }
}

Web/Controllers/AdminController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Web.Mediator.Arguments;
using Web.Mediator.Requests;

namespace Web.Controllers;

[Route("[controller]")]
public class AdminController : Controller
{

    private readonly IMediator _mediator;

    public AdminController(IMediator mediator)
    {
        _mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var carProducts = await _mediator.Send(new ShowRequest(new()));

        return View(new AdminViewModel(carProducts));
    }
        
    [HttpDelete]
    public IActionResult Delete(string mark, string model)
    {
        _mediator.Send(new RemoveRequest(new RemoveRequestArguments(mark, model)));

        return Ok();
    }

    [HttpPost]
    public IActionResult Add([FromForm] AddRequestArguments arguments)
    {
        _mediator.Send(new AddRequest(arguments));

        return RedirectToAction("Index");
    }

    [HttpPost("edit")]
    public IActionResult Edit(string model)
    {
        return RedirectToAction("Edit");
    }
}

Web/Controllers/CarsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Web.Mediator.Arguments;
using Web.Mediator.Requests;
using Web.ViewModels;

namespace Web.Controllers
{
    [Route("/")]
    [Route("[controller]")]
    public class CarsController : Controller
    {

        private readonly IMediator _mediator;

        public CarsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public  async Task<IActionResult> Index()
        {
            var carProducts = await _mediator.Send(new ShowRequest(new ()));

            return View(new IndexViewModel(carProducts));
        }

       
        [HttpPost("buy")]
        public async Task<IActionResult> Buy([FromForm] BuyRequestArguments arguments)
        {
            await _mediator.Send(new BuyRequest(arguments));
            return RedirectToAction("Index");
        }

        [HttpPost("sell")]
        public async Task<IActionResult> Sell([FromForm] SellRequestArguments arguments)
        {
            await _mediator.Send(new SellRequest(arguments));
            return RedirectToAction("Index");
        }



        [HttpGet("models/{mark}")]
        public async Task<IActionResult> GetModels(string mark)
        {
            var models = await _mediator.Send(new GetModelsRequest(new(mark)));
            return Json(models);
        }


    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    [Route("/Home")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/PartsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    [Route("[controller]")]
    public class PartsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Views/Admin/Index.cshtml
@model AdminViewModel
@addTagHelper *, Web


<link href="@Url.Content("~/css/StyleSheet.css")" rel="stylesheet" type="text/css" />

<table>
    <tr>
        <th>Марка</th>
        <th>Модель</th>
        <th>Цена</th>
        <th>Количество</th>
    </tr>
    @foreach (var product in Model.Products)
    {
        <tr>
            <td>@product.Subject.Mark</td>
            <td>@product.Subject.Model</td>
            <td>@product.Price</td>
            <td>@product.Count</td>
            
            <td>
                <button asp-method="Delete" asp-controller="Admin" asp-action="Delete" asp-route-mark="@product.Subject.Mark", asp-route-model="@product.Subject.Model">Удалить</button>
                <button asp-method="Post" asp-controller="Admin" asp-action="Edit" asp-route-mark="@product.Subject.Mark", asp-route-model="@product.Subject.Model">Изменить</button>
            </td>
        </tr>
    }
</table>

<partial name="AddForm"/>

Web/Views/Cars/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model Web.ViewModels.IndexViewModel
<div class="container mx-auto pt-2">
    <div class="row justify-content-center">
        @foreach (var product in Model.Products)
        {
            <div class="car-card p-3 m-2 bg-white" style="width: 18rem;">
                <div class="col">
                    <div class="row pb-3">
                        <div class="col-9">
                            <span class="text-black-50 text-uppercase" style="font-size: 0.7em; font-weight: bold;">@product.Subject.Mark</span>
                            <h5 class="card-title">@product.Subject.Model</h5>
                        </div>
                        <div class="col-3">
                            <a class="float-end btn btn-outline-danger" style="display: block;" href="#" role="button"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    @*Remove image url*@
                    <img class="card-img-top" src="https://im0-tub-by.yandex.net/i?id=16e21a518f766976c0ffe752a44eb2ec-l&n=13" alt="Car image">
                    <div class="row p-1">
                        <div class="col-6">
                            <span class="text-black-50 fw-bold">Brand:</span><span class="fw-bold text-uppercase"> @product.Subject.Mark</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            @*Refactor margin and font size*@
                            <p class="fw-bold" style="font-size: 1.55em; margin: 0;">$@product.Price</p>
                        </div>
                        <div class="col d-grid">
                            @using (Html.BeginForm("CarsController", "Buy", FormMethod.Post))
                            {
                                 @Html.Hidden("id", product.Id)
                                <input type="submit" value="Buy" class="btn btn-danger" style="width: 100%;"/>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<partial name="BuyForm" model="Model.BuyFormViewModel" />

<partial name="SellForm" model="Model.SellFormViewModel" />

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Autoshop";
}
<!-- Banner start -->
<style>
    .block-banner {
        background-image: url(https://spb.ananasposter.ru/image/catalog/poster/cars/81/15161.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
        height: 500px;
    }

    .blur {
        background: rgba(0, 0, 0, 0.5);
        backdrop-filter: blur(3px);
        height: 500px;
        width: 100%;
    }
</style>
<div class="position-relative overflow-hidden text-center block-banner ">
    <div class="blur">
        <div class="col-md-5 p-lg-5 mx-auto">
            <h1 class="display-5 fw-light text-uppercase text-white">are you looking</h1>
            <h1 class="display-4 fw-bolder text-uppercase text-warning">FOR A COOL CAR?</h1>
            <p class="lead fw-normal banner-description text-white">Autoshop is a prestigious car supermarket. We offer a friendly and efficient service for the purchase and repair of vehicles.</p>
            <a class="btn btn-light text-uppercase" href="#">Find your vehicle</a>
        </div>
    </div>
</div>
<!-- Banner end -->
<!-- Information section start -->
<div class="container px-3 py-4">
    <div class="row">
        <div class="col-md-6 px-5 my-sm-3">
            <h2>Heading 1</h2>
            <p class="text-justify">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </p>
        </div>
        <div class="col-md-6 px-5 my-sm-3">
            <h2>Heading 2</h2>
            <p class="text-justify">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </p>
        </div>
    </div>
</div>
<!-- Information section end -->

Web/Views/Parts/Index.cshtml
<div>
    
    404 - запчастей никогда не будет
</div>

Web/Views/Shared/AddForm.cshtml
@using Web.Mediator.Arguments
 

<form asp-controller="Admin" asp-action="Add" method="post">
    <fieldset>
        <legend>
            Добавить
        </legend>

        <br/>

        <label>
            Марка:
            <input name="@nameof(AddRequestArguments.Mark)"/>
        </label>

        <br/>

        <label>
            Модель:
            <input name="@nameof(AddRequestArguments.Model)"/>
        </label>

        <br/>

        <label>
            Количество:
            <input name="@nameof(AddRequestArguments.Count)" type="number" min="0"/>
        </label>

        <br/>

        <label>
            Цена:
            <input name="@nameof(AddRequestArguments.Price)" type="number" min="0"/>
        </label>

        <br />

        <input type="submit" value="Отправить"/>
    </fieldset>
   

</form>

Web/Views/Shared/BuyForm.cshtml
@using Web.Mediator.Arguments
@model Web.ViewModels.BuyFormViewModel

<form asp-controller="Cars" asp-action="Buy" method="post" id="buy">
    <fieldset>
        <legend>
            Покупка
        </legend>
        
        <label>
            Введите марку:
            <select name="@nameof(BuyRequestArguments.Mark)" asp-items="@(Model.Marks.Select(mark => new SelectListItem(mark, mark)))"></select>
        </label>
        
        <br/>
        
        <label>
            Введите модель:
            <select name="@nameof(BuyRequestArguments.Model)" asp-items="@(Model.Models.Select(model => new SelectListItem(model ,model)))"></select>
        </label>
        
        <br/>
        
        <label>
            Количество:
            <input name="@nameof(BuyRequestArguments.Count)" type="number" value="1" min = "0", max = "@Model.MaxCount"/>
        </label>
        
        <br />
        <input type="submit" value="Отправить"/>
    
    
    </fieldset>
</form>


<script>
    document.addEventListener('DOMContentLoaded',
        () => {
            attach_handler(document.getElementById("buy"));
        });
  
</script>

Web/Views/Shared/SellForm.cshtml
@using Web.Mediator.Arguments
@model Web.Models.SellFormModel

<form asp-controller="Cars" asp-action="Sell" method="post" id="sell">
    <fieldset>
        <legend>
            Продажа
        </legend>
        
        <label>
            Введите марку:
            <select name="@nameof(SellRequestArguments.Mark)" asp-items="@(Model.Marks.Select(mark => new SelectListItem(mark, mark)))"></select>
        </label>
        
        <br/>
        
        <label>
            Введите модель:
            <select name="@nameof(SellRequestArguments.Model)" asp-items="@(Model.Models.Select(model => new SelectListItem(model ,model)))"></select>
        </label>
        
        <br/>
        
        <label>
            Количество:
            <input name="@nameof(SellRequestArguments.Count)" type="number" value="1" min = "0"/>
        </label>
        
        <br />
        <input type="submit" value="Отправить"/>
    
    
    </fieldset>
</form>


<script>
    document.addEventListener('DOMContentLoaded',
        () => {
            attach_handler(document.getElementById("sell"));
        });
  
</script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AUTORL</title>
    <link rel="stylesheet" href="~/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="d-flex flex-column" style="background-color: #f2f2f2;">
    <div id="page-content">
        <header role="banner">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="container">
                    <div class="col-3">
                        <a class="navbar-brand logo-link" asp-controller="Home"><span>Auto</span><span class="red-logo">shop</span></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse">
                        <div class="col-9  d-flex justify-content-center">
                            <ul class="navbar-nav m-auto pl-lg-5 pl-0 menu">
                                <li class="nav-item">
                                    <a class="nav-link text-white menu-link" asp-controller="Home">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white menu-link" asp-controller="Cars">Cars</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white menu-link" href="#">Shops</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white menu-link" href="#">About</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-3">
                            <ul class="navbar-nav float-end">
                                <li class="nav-item">
                                    <a class="text-white" href="#"><i class="mx-2 fa fa-sign-in-alt"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
    </div>
    <footer class="flex-shrink-0 py-4 bg-dark text-white">
        <div class="container text-center">
            <small>Footer</small>
        </div>
    </footer>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>